stages:
  extract:
    cmd: PYTHONPATH=. python data_pipeline/scripts/data_extraction.py
    deps:
      - data_pipeline/data/raw
      - data_pipeline/scripts/data_extraction.py
    outs:
      - data_pipeline/data/extracted

  preprocess:
    cmd: PYTHONPATH=. python data_pipeline/scripts/preprocess.py
    deps:
      - data_pipeline/data/extracted
      - data_pipeline/scripts/preprocess.py
    outs:
      - data_pipeline/data/cleaned

  embed:
    cmd: PYTHONPATH=. python data_pipeline/scripts/store_in_chromadb.py
    deps:
      - data_pipeline/data/cleaned
      - data_pipeline/scripts/store_in_chromadb.py
    outs:
      - data_pipeline/data/vector_db

  validate:
    cmd: PYTHONPATH=. python data_pipeline/scripts/validate_data.py
    deps:
      - data_pipeline/scripts/validate_data.py
      - data_pipeline/data/cleaned
    outs:
      - data_pipeline/data/validated_policies
      - data_pipeline/logs/validation_report.csv


