stages:
  extract:
    cmd: python data_pipeline/scripts/data_extraction.py
    deps:
      - data_pipeline/data/raw
      - data_pipeline/scripts/data_extraction.py
    outs:
      - data_pipeline/data/extracted

  preprocess:
    cmd: python data_pipeline/scripts/preprocess.py
    deps:
      - data_pipeline/data/extracted
      - data_pipeline/scripts/preprocess.py
    outs:
      - data_pipeline/data/cleaned

  embed:
    cmd: python data_pipeline/scripts/store_in_chromadb.py
    deps:
      - data_pipeline/data/cleaned
      - data_pipeline/scripts/store_in_chromadb.py
    outs:
      - data_pipeline/data/vector_db
